### ISSUE TITLE
[feature request] Alt-tab support, fake full-screen support option.

### ISSUE THREAD

**Issue by qqw1235f** [Blinue/Magpie#16]
Hello, thank you for this amazing program. 
Here are few suggestions:
1. Would be nice to have the ability to alt-tab (switch to another windows) without magpie stopping working
2. Maybe add fake full screen option (Fake fullscreen is a borderless window that is the same size as your desktop resolution. You can pop up your start menu or open some other window and it will sit on top of the game.) Also works for suggestion №1.
Thanks!

**Comment by Blinue** [comment]
Thanks for your advice.

The most difficult part of enlarging a window is the handling of user input. I can make a window cover the desktop, but I can't map the mouse event back to the source window, because different windows handle input in completely different ways.

Magpie is already using "fake full screen" technology, but the difference is that this full screen window is always on top and cannot receive focus. Therefore, user input can work as if there is no full screen window.

For this reason, the full-screen window must be closed when the source window loses focus because it will **obscure all other windows**.

Your suggestion is difficult to implement. An alternative is to make Magpie remember the source window and automatically recreate the full-screen window when it regains focus, but this may not be what you want.

**Comment by qqw1235f** [comment]
Okay, thank you very much for such detailed reply, i understand now.

I asked about fake fullscreen because i wanted to put another unfocused windows on top of magpie window, but doesn't seem to be possible. It's nothing important, so forget about this part. 

> An alternative is to make Magpie remember the source window and automatically recreate the full-screen window when it regains focus, but this may not be what you want.

Actually would be great, as long as you make it into tickbox or something, so you can disable or enable this feature anytime you want in magpie main window with all other settings. Unless it's too much work to implement, of course.
I asked about this because sometimes i want to alt-tab from game window into browser, look-up walkthrough guide and then alt-tab back into game. 
This is what i meant by switching to another window.

**Comment by Blinue** [comment]
I've added this feature to the task list.
