### ISSUE TITLE
Ability to configure time for start scale ("Scale after 5s")

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Blinue/Magpie#258]
### Expected behavior 预期的功能

Setting for start time. 5 seconds for me it is a lot.

**Comment by Blinue** [comment]
Use the hotkey instead.

**Comment by bloc97** [comment]
@Blinue slightly off-topic, but I'm not sure why but in some games/programs the hotkey does not work (pressing it does nothing), while the "scale after 5s" button work. I have tried changing the hotkey to no effect.

**Comment by Blinue** [comment]
Have you tried running Magpie as an administrator?

**Comment by 0x4E69676874466F78** [comment]
Why then do need this button?
If there is a need for button, why not give the opportunity to set a convenient number of seconds?

**Comment by Blinue** [comment]
This button is intended to be used when the hotkey does not work or when the keyboard is not convenient to use. 

If more people request this feature, I'll add it. For now, you can modify the source code instead.

Change this constant to the seconds you want to wait.

https://github.com/Blinue/Magpie/blob/629b20ba4e864e3612e591ba86b810c4ba0c7bbb/Magpie/MainWindow.xaml.cs#L36-L37

**Comment by MuhammadUsmanMithani** [comment]
Maybe add this option in a basicConfig.json file or from registry editing/however u store other settings?

As for "hotkey not working", previously, it was not working for me either when it was defaulted to Alt+F11, but due to "F11", some games registered it incorrectly, and started weirding up. Now, as Alt+F10, it works perfectly without any issues

**Comment by Blinue** [comment]
This feature will be available in v0.10.

**Comment by Blinue** [comment]
v0.10 is released 🎉
