### ISSUE TITLE
Mouse cursor cannot move to monitors above the game in fullscreen

### ISSUE THREAD

**Issue by MarvNC** [Blinue/Magpie#270]
### Magpie version 程序版本

0.8.0

### Windows version 系统版本

Windows 10 Enterprise 19043.1415

### Related screenshot (optional) 相关截图（可选）

![ApplicationFrameHost_Settings_2022-01-08_19-50-25](https://user-images.githubusercontent.com/17340496/148668713-92d819d3-014a-48d6-903b-77a3dca7e2f3.png)

### Reproduction steps 复现步骤

- Have two monitors installed vertically
- Run a game using Magpie on the bottom monitor (monitor 1)
- Attempt to move the mouse cursor from the main monitor (monitor 1) to the top monitor (monitor 4)

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7834443/Magpie.log)

**Comment by Blinue** [comment]
Works well in my case.

![image](https://user-images.githubusercontent.com/34770031/148669048-18a7fdc1-24d2-44d5-ae10-80a6042bec23.png)

Can the cursor be moved to 2 and 3?

**Comment by MarvNC** [comment]
Yes, it can be moved to 2 and 3. I did not think of this earlier, but monitor 4 is not connected to the graphics card like monitors 1-3 and is instead connected via a USB C cable, perhaps this is part of the issue?

**Comment by Blinue** [comment]
I'm using [MonitorFromPoint](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfrompoint) to find the monitors that the cursor can be moved to, maybe this API can't detect monitor 4. In order to find out the problem, please do some tests.

1. Can monitor 4 be seen in Settings > System > Display?
2. Which monitors will be used when this option is selected?
![image](https://user-images.githubusercontent.com/34770031/148670654-f947c6f4-a761-4d37-aba9-b17e7a1c4561.png)
3. Which monitors will be used when this options is selected and the game window spans monitor 1 and 4?
![image](https://user-images.githubusercontent.com/34770031/148670721-489dc326-8af0-428c-8780-ee5fecbafb98.png)

**Comment by MarvNC** [comment]
1. Yes, that is where I took the screenshot.
2. This option makes the game run across all 4 monitors.
3. This option makes the game run across monitors 1 and 4.

**Comment by Blinue** [comment]
Perhaps your multi-monitor configuration looks like this

![image](https://user-images.githubusercontent.com/34770031/148673826-0cd9d940-dc11-4c21-af96-33609752afcf.png)

Displays 1 and 4 are not adjacent to each other, so the cursor cannot move between them.

**Comment by MarvNC** [comment]
Thanks, that was the issue.

**Comment by Blinue** [comment]
I'll fix it soon, thanks for the report!
