### ISSUE TITLE
Cannot see mouse cursor in some apps when upscaled

### ISSUE THREAD

**Issue by NotADinosaur** [Blinue/Magpie#275]
### Magpie version 程序版本

0.8.0

### Windows version 系统版本

win10 21h1

### Reproduction steps 复现步骤

1: upscale window
2: cursor will disappear (only with some programs like minecraft, most work)
it still works and I can click things, I just can't see where it is.

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/7874070/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/7874071/Runtime.log)
I tried changing some settings to see if it would fix it, but it happened with default settings too

**Comment by Blinue** [comment]
Thanks for the report. The default shortcut of Magpie (Alt+F11) and the fullscreen shortcut of Minecraft (F11) are in conflict. The solution is to change the hotkey of Magpie.

**Comment by bliu13** [comment]
I am running into the same issue trying to play Starcraft 2. I am not sure what the problem is.

Here are my settings:
- Scaling Mode: FSR
- Capture Mode: Graphics Capture
- Auto scale when in foreground: On
- 3D Gaming Mode: On
- Graphics Card: Default
- Display FPS Counter: On
- Vsync: On
- Disable window resizing while scaled: Off
- Capture title bar: Off
- Custom Crop: Off
- Draw cursor: Off (Tried turning it on, no difference)
- Adjust cursor speed while scaled: Off (Tried turning it on, no difference)
- Disable DirectFlip: Off

[magpie.log](https://github.com/Blinue/Magpie/files/12065215/magpie.log)
