### ISSUE TITLE
Can be used on multiplayer games ?

### ISSUE THREAD

**Issue by ali-exacute** [Blinue/Magpie#28]
Hello . first of all , thank you for this awesome release !

i have a question , does this works with online multiplayer games ?
or does anticheats catch this as a cheat ?

**Comment by Blinue** [comment]
I can't give a definitive answer because I don't know how anti-cheat works.

Magpie does two operations on the game window.

1. it captures frames of the window. This is usually a safe operation, because recording a game will obviously not be judged as cheating.

2. If you select process injection, Magpie will inject a DLL into the game process, which is a dangerous operation and may be considered cheating.

If you are going to use Magpie for multiplayer games anyway, do not use process injection.

**Comment by WhAtEvErYoUmEaN** [comment]
@Blinue is this still an issue? Since the drop-down is missing since roughly the 9th September i'd gather that this feature has been dropped.

In other words: do you still need to disable Injection and if yes, how do you disable it?

**Comment by WhAtEvErYoUmEaN** [comment]
I just ran through a few other Github issues with Google Translate. In #121 [Google Translate jp->en link](https://github-com.translate.goog/Blinue/Magpie/issues/121?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=de#issuecomment-919610809) Blinue states injection is gone. Thanks!
