### ISSUE TITLE
Drag to rearrange scaling modes

### ISSUE THREAD

**Issue by MarvNC** [Blinue/Magpie#485]
### Expected behavior 预期的功能

The feature of creating and customizing scaling modes is great. I would love if you could drag the scaling modes to reorder them.

**Comment by Blinue** [comment]
I have also considered this feature, but unfortunately it's technically not feasible due to WinUI's very limited support for drag and drop. Firstly, the scaling mode card can be expanded, which means it accepts click events, conflicting with drag and drop. Additionally, the effects also support drag and drop, nesting one draggable element within another is very difficult.

Anyway, thank you for the advice.
