### ISSUE TITLE
Scaling is cancelled when a RPG Maker MZ game reloads

### ISSUE THREAD

**Issue by necaran** [Blinue/Magpie#508]
### Magpie version 程序版本

v0.10.0

### Windows version 系统版本

win10

### Reproduction steps 复现步骤

1. Run a RPG Maker MZ game
2. Start scaling with Magpie
3. Reload the game by pressing F5

The reason for this behavior is that the class name of the window changes when the game reloads. When the game first launched the class is `Chrome_WidgetWin_1` and if reloaded it became `Chrome_WidgetWin_2`. The number increases with every reload. Because of this behavior, it would also fail to apply the profile for a RPG Maker MZ game after reload because `classNameRule` does not match.

### Log files 日志文件

-

**Comment by eriforce** [comment]
maybe there could be a toggle to disable/ignore classNameRule matching for a profile or an application?

**Comment by Blinue** [comment]
I'm investigating the issue.

**Comment by eriforce** [comment]
> @eriforce I don't think it's a good idea because most users don't even know what window classes are.

I mean it could something like "match with path only", not necessary to mention `class`.

**Comment by Blinue** [comment]
> I mean it could something like "match with path only", not necessary to mention class, just my random idea.

That's true. However, we already have [the logic to handle WPF windows](https://github.com/Blinue/Magpie/blob/b1445e9e7912d483051c9914e79d67c6ff67e5aa/src/Magpie.App/ProfileService.cpp#L10), so it would be easier to extend it based on that.

> I'm also curious about the reason class name is taken into consideration, is it for processes with multiple windows?

This is a carefully considered decision.

* It can avoid scaling pop-ups.
* The profiles are for windows rather than processes. If a process has multiple windows of different types, it is not appropriate for them to share the same profile.
