### ISSUE TITLE
Graphics Capture 失败：The service cannot be started

### ISSUE THREAD

**Issue by LOuroboros** [Blinue/Magpie#517]
### Magpie version 程序版本

 v0.9.1 / v0.10.0

### Windows version 系统版本

Windows 11 22H2 (Build 22621.1413)

### Reproduction steps 复现步骤

I'm merely trying to upscale a game's window normally, that's it.

Graphics Capture, GDI, DwmSharedSurface. None of those capture methods work.

Desktop Duplication does work, but sadly, it doesn't play nice with the capturing methods of [ShareX](https://github.com/ShareX/ShareX). ShareX sees my entire Windows desktop whenever I have a game upscaled using Magpie's Desktop Duplication capture method.

This started to happen a few weeks back when I formatted my PC. I used to be able to use Magpie just fine before.

For whatever it's worth, I noticed in Windows' Services editor that there's a service called "CaptureService_429b9".
Its Startup Type is "Manual".
If I try to close Magpie, start the service and then open Magpie, the 3 aforementioned capture methods still refuse to work.

May I get a list of the Windows Services that Magpie requires in order to work?

### Log files 日志文件

This is the log generated after trying to upscale via the Graphics Capture method.
[magpie.log](https://github.com/Blinue/Magpie/files/11088114/magpie.log)

**Comment by Blinue** [comment]
I have no knowledge about the implementation details of Graphics Capture, but if it's not working, it's possible that there's an issue with your driver. It might be worth considering submitting a bug report to Microsoft.

**Comment by LOuroboros** [comment]
I already reinstalled my GPU driver a couple of times since I submitted this Issue ticket, and as I always do, with clean settings too.

That didn't solve anything though :/

I've been looking around ever since I submitted this ticket. Found comments across the internet telling me how I should have certain services like the Windows Deployment Management service or the Application Information service enabled, but I have them both up and running.

I can't find anything more specific on the internet. Any ideas, besides contacting Microsoft?

**Comment by Blinue** [comment]
From the error message, it seems that a certain service is unable to start, but the message is too general and doesn't indicate which service is causing the issue and why it cannot start. Since you are the only one experiencing this problem, I believe it may be due to certain configurations on your computer.

Magpie utilizes the Graphics Capture API, but if the API itself is experiencing issues, I am not sure how to resolve them. One way to get Microsoft's attention is to report an issue to [PowerToys](https://github.com/microsoft/PowerToys), which uses the Graphics Capture API to implement the Screen Ruler feature. If you encounter an error while using this feature, submitting an issue to PowerToys may help resolve your problem.
