### ISSUE TITLE
use window title instead of file path

### ISSUE THREAD

**Issue by Michael1297** [Blinue/Magpie#561]
### Expected behavior 预期的功能

Сan use these features to create a profile for individual pages when you scale your browser.
Lossless Scaling added this in the latest version. I will need it if you add https://github.com/Blinue/Magpie/issues/559
- Ability to specify the window title for the profile;
- Ability to use wildcard characters "?" and "*" for the profile filter;

### Alternative behavior (optional) 近似的功能（可选）

add a separate field where you can enter the title of the window during profile creation
For example: `*.mp4 - Google Chrome`

**Comment by Blinue** [comment]
Magpie uses program path and window class name to identify windows, this is a well-thought-out decision. I know some programs use titles to identify windows, but I don’t think that’s a good idea. Separate profiles for browser tabs will not be supported.

**Comment by Agitatio** [comment]
There are games that unpack when launched and use the unpacked exe. Unfortunately, the unpacked exe is placed in a temporary folder with new name every time you launch these games, so matching by path is impossible for them. At least an option to match by full exe name instead of full path would've been greatly appreciated for such cases.
