### ISSUE TITLE
Allow Magpie to project to a second monitor

### ISSUE THREAD

**Issue by kanjieater** [Blinue/Magpie#742]
### Expected behavior 预期的功能

If the game is on monitor A, Magpie can show the fullscreen on monitor B. Currently the magpie display and the game display monitor have to be the same.

**Comment by Blinue** [comment]
What is the use case? I think it is necessary to use the same screen to cover the original window.

**Comment by kanjieater** [comment]
The use case is I want the window to run on my primary display but the fullscreen to be projected to my secondary display. My primary display is small but my secondary display is big.

**Comment by Blinue** [comment]
I still don’t see the point of this, why not just move the window you want to scale to the second screen?

**Comment by Blinue** [comment]
Thank you for your suggestion, but this feature is not very useful, and it may cause confusion, as well as increase the complexity of the configuration. It may be necessary to scale to other screens in very specific scenarios, but this is not common, and there is no need to make everyone pay for it.

**Comment by TitaniaEXE** [comment]
Hello, I believe there would be one use case for this feature. 

A common way to use CRT TVs on modern systems involves outputting "super-resolutions" such as 2560 by 240p or 480i, which are displayed anamorphically on the TV. It is fairly rare for modern games to support these painlessly, due to the combination of non-linear scaling and extremely low vertical resolution. On Linux, this can be circumvented using xrandr scaling, but no such feature exists on Windows. 

If we could tie a specific display to a profile, it would make it a cinch to run effectively any game on these displays.
