### ISSUE TITLE
Desktop Duplication - Window is too large to capture!?

### ISSUE THREAD

**Issue by Baten84** [Blinue/Magpie#746]
### Magpie version 程序版本

0.9.1

### Windows version 系统版本

Windows 11

### Related screenshot (optional) 相关截图（可选）

![image](https://github.com/Blinue/Magpie/assets/121767249/ce58e9ab-c7c5-43c2-bef1-54b547641d04)

### Reproduction steps 复现步骤

I tried the Desktop Duplication mode, however no matter which game I try, it always throws the "Window is too large to capture" error. The game window is 1280x720, the desktop resolution is 1366x768.

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/13245602/Magpie.log)

**Comment by kato-megumi** [comment]
Try to use the latest version.
https://github.com/Blinue/Magpie/releases/tag/v0.10.3

**Comment by Baten84** [comment]
Is this a known issue and fixed in the latest release then?

My theory is that it's because I use a laptop. The laptop screen is 1080p. However I use a secondary screen, so it might be that magpie tries to scale the 1080p screen?

**Comment by Baten84** [comment]
So I tried the newest version and it doesn't do anything. Desktop duplication doesn't work.

**Comment by Blinue** [comment]
As shown in your screenshot, the window cannot be fully displayed on the screen, and a part of it is blocked by the taskbar. Your screen height is 768 pixels, and after subtracting the height of the taskbar, title bar, and menu bar, the remaining space is not enough to accommodate the client area of 720 pixels high.

Desktop Duplication is similar to taking a screenshot, and because the client area of this window cannot be fully displayed, the scaling fails. You can set the taskbar to auto-hide, and the scaling will succeed.

**Comment by hooke007** [comment]
From your screenshot, it seems the program is scaled by system first( the length of width is over 1280).
You could also disable its scaling first.
