### ISSUE TITLE
插针是否可以实现？

### ISSUE THREAD

**Issue by kikilloy** [Blinue/Magpie#815]
### Expected behavior 预期的功能

AMD3.0的插针技术是真不错，使我1066旋转，但也要游戏支持AMD3.0（或者替换DLSS3.0），Lossless.Scaling也弄了一个插针功能（LSFG），在某些游戏用了感觉没什么延迟（驱动面板开低延迟模式，限60帧率），Magpie 是否有这类功能的开发计划？我挺期待在Magpie 能用上插针。毕竟在Lossless.Scaling用FSR1.0提升很差，不如Magpie，我个人更喜欢用Magpie

**Comment by hooke007** [comment]
这种后处理补帧没有神秘，都是滞后帧为代价补中间帧。

**Comment by kikilloy** [comment]
滞后帧我个人可以接受，反正插针一般也就在非竞技类游戏使用，延迟高可以通过开低延迟模式弥补一下，用了Lossless.Scaling的插针的确可以在一定程度上提高流畅性，拖影个人感觉不明显，但Lossless.Scaling对GPU性能花费要求过高，插针效果并不好，除非进一步降低游戏分辨率、画质，以降低游戏在GPU上的性能花费，将剩下的性能匀给插针，所以希望Magpie能做出这个，毕竟Magpie的性能花费比Lossless.Scaling好多了

**Comment by hooke007** [comment]
忽视劣质的画面瑕疵，抛开作者的计划不谈，当下也没有现成开放的的超高效的后处理补帧算法。当然你如果能直接PR一个现成的方案，我想作者应该不会拒绝（

**Comment by Blinue** [comment]
我不想实现补帧有两个原因：
1. 后处理补帧很难有好效果，而且还会增加延迟。游戏引擎因为可以使用运动矢量和深度缓冲所以补帧效果更好，但归根结底，补帧所提高的帧率是假的，不要上了老黄的当。
2. Magpie 的目的是提高游戏画质而不是性能，和 LS 不一样。

**Comment by REB-ro** [comment]
> 我不想实现补帧有两个原因：
> 
> 1. 后处理补帧很难有好效果，而且还会增加延迟。游戏引擎因为可以使用运动矢量和深度缓冲所以补帧效果更好，但归根结底，补帧所提高的帧率是假的，不要上了老黄的当。
> 2. Magpie 的目的是提高游戏画质而不是性能，和 LS 不一样。

Good afternoon, Blinue.

Lossless Scaling's frame generation is different from FSR3 and DLSS3, as you said it doesn't use vectors, etc., but it manages to deliver screen fluidity. I believe the dev is using a similar technique to "Black Frame Insertion" (BFI), but instead of a black/empty frame, it repeats an entire frame without interpolating with the next frame. That's why Lossless Scaling's frame generation gives a different feeling than FSR3 and DLSS3, but the fluidity remains. If Magpie can do something similar, even if only in the testing field, it would be a good thing, because I've seen people say that Magpie is already capable of using BFI.

Lossless Scaling's frame generation is better in new versions of the software, but I trust Magpie more and I think you guys can achieve the same thing, better and with more trustfully.

Thanks, Bro.

**Comment by Blinue** [comment]
From what I understand, Lossless Scaling employs machine learning algorithms to anticipate intermediate frames. This likely results in a one-frame latency as it interpolates predicted frames between existing ones, thereby doubling the framerate.

Your attention and confidence in Magpie are much appreciated, yet there are no immediate plans to implement frame generation. This decision stems not only from the fact that it falls outside Magpie’s core objectives but also due to a backlog of highly requested features that take precedence. Nonetheless, should there be community contributions, I would gladly consider them for review.

**Comment by Linx-ESP** [comment]
Frame doubling would help some 30fps games/emulators with framepacing in freesync displays (since freesymc doesnt trigger under 45Hz in some displays)

This would help as a 50 to 25 fps would be seen from.the monitor as 100 to 50 and be kept with freesync

**Comment by satoshils** [comment]
> 我不想实现补帧有两个原因：
> 
> 1. 后处理补帧很难有好效果，而且还会增加延迟。游戏引擎因为可以使用运动矢量和深度缓冲所以补帧效果更好，但归根结底，补帧所提高的帧率是假的，不要上了老黄的当。
> 2. Magpie 的目的是提高游戏画质而不是性能，和 LS 不一样。

不管补帧的帧率真假与否，视觉上是真的效果明显，丝滑了很多很多，最多1/30秒的延迟除了那些对操作十分敏感的格斗游戏外，基本是没啥影响，还是建议大大考虑一下

**Comment by hooke007** [comment]
> 不管补帧的帧率真假与否，视觉上是真的效果明显，丝滑了很多很多，最多1/30秒的延迟除了那些对操作十分敏感的格斗游戏外，感官上基本是没啥影响的，还是建议大大考虑一下

还有个更现实的前置问题，有没有满足这个条件的可用开源模型

**Comment by satoshils** [comment]
> > 不管补帧的帧率真假与否，视觉上是真的效果明显，丝滑了很多很多，最多1/30秒的延迟除了那些对操作十分敏感的格斗游戏外，感官上基本是没啥影响的，还是建议大大考虑一下
> 
> 还有个更现实的前置问题，有没有满足这个条件的可用开源模型

实在不行兼容一下LosslessScaling也能达到同样效果。双开测试过，虽然只能显示完整画面的一部分，但这部分放大和补帧的效果都特别好，只要处理好显示部分的兼容就可以

**Comment by satoshils** [comment]
> 这不是已经回答过了吗 [#1128](https://github.com/Blinue/Magpie/discussions/1128)
> 
> 你也可以向LS提交要求做兼容magpie

提交了，但那边基本没人说汉语，帖子一会儿就沉没了
