### ISSUE TITLE
Anime4K v4来啦

### ISSUE THREAD

**Issue by Tubunu** [Blinue/Magpie#87]

**Comment by 412907593** [comment]
> Magpie目前对Anime4K的支持不是很好，我更推荐使用ACNet。我最近主要聚焦于优化性能，因此不会立刻跟进。

玩一些低分辨率的galgame用ACNet更好吗

**Comment by Blinue** [comment]
建议你每个算法都尝试一下，或者参考wiki自定义缩放

**Comment by Z-Dante** [comment]
I've tested all of them the upscale shaders and most of them work wonderfully and produces great results👍.
The only problem I've found is that the Anime4K_Restore_VL shader gives every image a slight blue tint. I'm not really sure if it's intentional or not. To illustrate: 
Original: 
![Original Image](https://user-images.githubusercontent.com/34379513/139655484-c8b78933-d3e9-447e-bd9c-8a38620b5ff3.png)
Anime4K_Restore_VL: 
![Anime4K_Restore_VL Image](https://user-images.githubusercontent.com/34379513/139655572-52f3081d-bccf-4f07-a98f-473aceafdc9e.png)
The blue is not present in the Anime4K_Restore_M shader and that one works perfectly.


And if it's possible could please you also port the Soft and L variants of the anime4k shaders? I found the VL variant a bit too heavy for real-time use and the normal restore shaders seem to produce visible ringing artefacts.

**Comment by Blinue** [comment]
> The only problem I've found is that the Anime4K_Restore_VL shader gives every image a slight blue tint

Thanks for the report, I've just fixed it.

> And if it's possible could please you also port the Soft and L variants of the anime4k shaders?

I'll port them before v0.7 is released.
