### ISSUE TITLE
Select which GPU to use

### ISSUE THREAD

**Issue by Naizuri77** [Blinue/Magpie#88]
If we have more than one GPU it would be very useful to have the option to choose which one we want to use, so we can upscale without taking resources from the GPU that is running the game.

**Comment by DefectiveByDesign** [comment]
Windows 10 should theoretically already have options for this, under graphics setting control panel. I'm using the english translation version, and it seems like it is already doing it. Problem is, most of the upscaling modes are too intensive to not have FPS drop. I vastly prefer magpie over lossless scaling in terms of how it works, because it actually works with task switching and even restores the scaling mode. However, it's too slow for laptops.

To find GPU usage, you have to enable GPU and GPU Engine options in the windows task manager. It's just really hard to see when playing a game, so something like "see through windows" might help.

**Comment by Naizuri77** [comment]
Windows 10 has this option but it doesn't seems to work with two dedicated GPUs. I have a 5500 XT and a 1050 Ti, but Windows only lets me select the 5500 XT for both High Performance and Power Saving. I think that feature only works if one of the GPUs is an iGPU. That's why I wanted this option integrated into Magpie, so I could make it use the 1050 Ti instead of the 5500 XT. Maybe it's a bug with Windows, and I should be able to select the 1050 Ti, but regardless having the option integrated into Magpie would make it more reliable for cases like mine.

And I wouldn't be surprised if people are accidentally forking this program, it has received a lot of attention since it added FSR so some of them may not be too familiar with how Github works. I myself made a fork by accident that I already deleted when I only wanted to check other people's forks, so I wouldn't be surprised if other people are also forking it by accident and can't figure out how to delete it or just can't be bothered.

**Comment by Blinue** [comment]
https://github.com/Blinue/Magpie/releases/tag/v0.7.1
