### ISSUE TITLE
Support classNameRule partial match

### ISSUE THREAD

**Issue by nixxou** [Blinue/Magpie#904]
### Expected behavior 预期的功能

I have a game where the class name of the main window change at every boot.
It would be nice if either magpie support partial class name (like if the class of the window contains what's written in classNameRule, it's a match) or wildcards.

Like the game i play have a class like that : XWindow_xxxxxxxxxxx where the xxxxx part change at every boot.
I would like in my profile to write something like this : 
"classNameRule": "XWindow_",
or like this
"classNameRule": "XWindow_*",

**Comment by Blinue** [comment]
Rather than burdening users with these details, I prefer proactively adapting to these windows, much like we do for WPF and RPG Maker MZ.

https://github.com/Blinue/Magpie/blob/8f6a2721bade034f2cf979695a883a73b9d98391/src/Magpie.App/ProfileService.cpp#L10-L33

Can you provide the name of the game and the framework it uses?

**Comment by nixxou** [comment]
It's an obscure arcade game launched though teknoparrot, Dead Heat Riders.

**Comment by Blinue** [comment]
It's very helpful, thank you!
